version: '3.9'
services:
  rb-scores-frontend:
    image: zenoli/rb-scores-frontend
    build: .
    container_name: rb-scores-frontend
    ports:
      - "8080:80"
    env_file:
        - .env
  # rb-scores-backend:
  #   image: "zenoli/rb-scores-backend"
  #   ports:
  #     - "3000:3000"
